name: plunging-flow-analysis
channels:
  - conda-forge
dependencies:
  - python=3.8
  - bokeh>=2.0.0
  - cf_xarray
  - dask=2.20.0
  - dask-labextension>=2.0.0
  - distributed=2.20.0
  - hvplot
  - ipywidgets>=7.5
  - jupyter-server-proxy
  - jupyterlab>=2.0.0
  - matplotlib!=3.3.1
  - notebook
  - nodejs
  - netcdf4
  - numpy>=1.18.1
  - pandas<1.1
  - python-graphviz
  - scipy>=1.3.0
  - pip
  - tqdm
  - pip:
    - expectexception
